import type {
  ActivityEvent,
  Campaign,
  Market,
  Position,
} from "@/lib/types";
import type { Asset, ClaimPreviewStatus, Side } from "@/lib/types";
export interface StoredClaim { code: string; status: ClaimPreviewStatus; campaignName: string; campaignId: string; asset: Asset; side: Side; potentialPayout: number; marketProbability: number; cashoutPrice: number; expiresAt: number; message: string; claimedBy?: string; }

const now = () => Date.now();
const inMinutes = (m: number) => now() + m * 60_000;
const minutesAgo = (m: number) => now() - m * 60_000;
const collateral = { address: "0x0000000000000000000000000000000000000001", symbol: "tUSDC", decimals: 6 } as const;

export const markets: Market[] = [
  {
    id: "btc-15m-001",
    collateral,
    canCreateCampaign: true,
    asset: "BTC",
    question: "Will BTC finish this window UP?",
    upProbability: 0.57,
    downProbability: 0.43,
    bestUpCashout: 0.54,
    bestDownCashout: 0.4,
    status: "TRADING",
    liquidity: "HEALTHY",
    expiresAt: inMinutes(12.7),
  },
  {
    id: "eth-15m-001",
    collateral,
    canCreateCampaign: true,
    asset: "ETH",
    question: "Will ETH finish this window UP?",
    upProbability: 0.46,
    downProbability: 0.54,
    bestUpCashout: 0.43,
    bestDownCashout: 0.51,
    status: "TRADING",
    liquidity: "HEALTHY",
    expiresAt: inMinutes(12.7),
  },
  {
    id: "btc-1h-002",
    collateral,
    canCreateCampaign: true,
    asset: "BTC",
    question: "Will BTC finish this hour UP?",
    upProbability: 0.62,
    downProbability: 0.38,
    bestUpCashout: 0.59,
    bestDownCashout: 0.35,
    status: "TRADING",
    liquidity: "THIN",
    expiresAt: inMinutes(41),
  },
  {
    id: "eth-1h-002",
    collateral,
    canCreateCampaign: true,
    asset: "ETH",
    question: "Will ETH finish this hour UP?",
    upProbability: 0.51,
    downProbability: 0.49,
    bestUpCashout: 0.48,
    bestDownCashout: 0.46,
    status: "TRADING",
    liquidity: "HEALTHY",
    expiresAt: inMinutes(52),
  },
];

export const campaigns: Campaign[] = [
  {
    id: "cmp-001",
    collateral,
    name: "Somnia Hacker Night",
    marketId: "btc-15m-001",
    asset: "BTC",
    budget: 10,
    positionSize: 1,
    totalDrops: 20,
    claimedDrops: 14,
    upDistributed: 7,
    downDistributed: 7,
    cashOuts: 3,
    status: "LIVE",
    message:
      "You just received a live BTC prediction from Somnia Hacker Night.",
    createdAt: minutesAgo(24),
  },
  {
    id: "cmp-002",
    collateral,
    name: "Builder Night",
    marketId: "eth-15m-001",
    asset: "ETH",
    budget: 8,
    positionSize: 1,
    totalDrops: 16,
    claimedDrops: 16,
    upDistributed: 8,
    downDistributed: 8,
    cashOuts: 6,
    status: "SETTLED",
    message: "A live ETH prediction, on the house.",
    createdAt: minutesAgo(220),
  },
  {
    id: "cmp-003",
    collateral,
    name: "Community Watch Party",
    marketId: "btc-1h-002",
    asset: "BTC",
    budget: 25,
    positionSize: 1,
    totalDrops: 50,
    claimedDrops: 31,
    upDistributed: 16,
    downDistributed: 15,
    cashOuts: 9,
    status: "LIVE",
    message: "Pick a side before the window closes.",
    createdAt: minutesAgo(70),
  },
  {
    id: "cmp-004",
    collateral,
    name: "Conference Pack",
    marketId: "eth-1h-002",
    asset: "ETH",
    budget: 21,
    positionSize: 1,
    totalDrops: 42,
    claimedDrops: 30,
    upDistributed: 15,
    downDistributed: 15,
    cashOuts: 4,
    status: "LIVE",
    message: "Inside your attendee pack: one live prediction.",
    createdAt: minutesAgo(400),
  },
];

export const positions: Position[] = [
  {
    id: "pos-001",
    campaignId: "cmp-001", claimId: "claim-demo", marketId: "btc-15m-001", potentialGrossPayout: 1,
    asset: "BTC",
    side: "UP",
    quantity: 1,
    marketProbability: 0.57,
    cashoutPrice: 0.54,
    potentialPayout: 1,
    status: "ACTIVE",
    expiresAt: inMinutes(8.35),
    claimedFrom: "Somnia Hacker Night",
    claimedAt: minutesAgo(2),
    claimTx: "0x9a41c7e2b8d5f0a3c6194e7b25d8f0c3a1b6e94d",
    tokenId: "#mock-7741",
    network: "Somnia Shannon",
    probabilityHistory: [0.52, 0.53, 0.55, 0.54, 0.56, 0.57],
  },
  {
    id: "pos-002",
    campaignId: "cmp-004", claimId: "claim-eth-down", marketId: "eth-15m-001", potentialGrossPayout: 1,
    asset: "ETH",
    side: "DOWN",
    quantity: 1,
    marketProbability: 0.61,
    cashoutPrice: 0.59,
    potentialPayout: 1,
    status: "ACTIVE",
    expiresAt: inMinutes(4.7),
    claimedFrom: "Conference Pack",
    claimedAt: minutesAgo(11),
    claimTx: "0x77c1e8043b9a2f6d5e0c318a94b7d26f0e5a1c83",
    tokenId: "#mock-7742",
    network: "Somnia Shannon",
    probabilityHistory: [0.55, 0.57, 0.58, 0.6, 0.6, 0.61],
  },
  {
    id: "pos-003",
    campaignId: "cmp-002", claimId: "claim-won", marketId: "btc-15m-001", potentialGrossPayout: 1,
    asset: "BTC",
    side: "UP",
    quantity: 1,
    marketProbability: 1,
    cashoutPrice: 0,
    potentialPayout: 1,
    status: "WON",
    expiresAt: minutesAgo(30),
    claimedFrom: "Builder Night",
    claimedAt: minutesAgo(95),
    claimTx: "0x21bd9f4c7a3e05186d2b4c9e0f7a35c81d6b4920",
    tokenId: "#mock-7638",
    network: "Somnia Shannon",
    probabilityHistory: [0.48, 0.53, 0.61, 0.72, 0.88, 1],
  },
  {
    id: "pos-004",
    campaignId: "cmp-002", claimId: "claim-lost", marketId: "btc-15m-001", potentialGrossPayout: 1,
    asset: "BTC",
    side: "DOWN",
    quantity: 1,
    marketProbability: 0,
    cashoutPrice: 0,
    potentialPayout: 1,
    status: "LOST",
    expiresAt: minutesAgo(30),
    claimedFrom: "Builder Night",
    claimedAt: minutesAgo(96),
    claimTx: "0x5e0a83c14b7d296f0e5a1c8377c1e8043b9a2f6d",
    tokenId: "#mock-7639",
    network: "Somnia Shannon",
    probabilityHistory: [0.52, 0.47, 0.39, 0.28, 0.12, 0],
  },
  {
    id: "pos-005",
    campaignId: "cmp-003", claimId: "claim-sold", marketId: "eth-15m-001", potentialGrossPayout: 1,
    asset: "ETH",
    side: "UP",
    quantity: 1,
    marketProbability: 0.44,
    cashoutPrice: 0,
    potentialPayout: 1,
    status: "SOLD",
    soldFor: 0.61,
    expiresAt: minutesAgo(60),
    claimedFrom: "Community Watch Party",
    claimedAt: minutesAgo(180),
    claimTx: "0x8b3c2f9d16a4e70b5c8d2419f6a0e3b7d5c19248",
    tokenId: "#mock-7501",
    network: "Somnia Shannon",
    probabilityHistory: [0.5, 0.53, 0.58, 0.62, 0.6, 0.61],
  },
];

export const claims: StoredClaim[] = [
  {
    code: "demo",
    status: "AVAILABLE",
    campaignName: "Somnia Hacker Night",
    campaignId: "cmp-001",
    asset: "BTC",
    side: "UP",
    potentialPayout: 1,
    marketProbability: 0.57,
    cashoutPrice: 0.54,
    expiresAt: inMinutes(8.35),
    message:
      "You just received a live BTC prediction from Somnia Hacker Night.",
  },
  {
    code: "eth-down",
    status: "AVAILABLE",
    campaignName: "Conference Pack",
    campaignId: "cmp-004",
    asset: "ETH",
    side: "DOWN",
    potentialPayout: 1,
    marketProbability: 0.54,
    cashoutPrice: 0.51,
    expiresAt: inMinutes(11),
    message: "Inside your attendee pack: one live prediction.",
  },
  {
    code: "claimed",
    status: "ALREADY_CLAIMED",
    campaignName: "Somnia Hacker Night",
    campaignId: "cmp-001",
    asset: "BTC",
    side: "UP",
    potentialPayout: 1,
    marketProbability: 0.57,
    cashoutPrice: 0.54,
    expiresAt: inMinutes(8),
    message: "",
  },
  {
    code: "expired",
    status: "EXPIRED",
    campaignName: "Builder Night",
    campaignId: "cmp-002",
    asset: "ETH",
    side: "UP",
    potentialPayout: 1,
    marketProbability: 0.5,
    cashoutPrice: 0,
    expiresAt: minutesAgo(20),
    message: "",
  },
];

export const activity: ActivityEvent[] = [
  { id: "act-1", kind: "CLAIM", text: "0x81…42 claimed BTC UP", at: minutesAgo(2) },
  { id: "act-2", kind: "CASHOUT", text: "BTC UP cashed out at $0.61", at: minutesAgo(6) },
  { id: "act-3", kind: "CLAIM", text: "0x71…39 claimed BTC DOWN", at: minutesAgo(9) },
  { id: "act-4", kind: "SETTLED", text: "Campaign “Builder Night” settled", at: minutesAgo(31) },
  { id: "act-5", kind: "CLAIM", text: "0x2f…c1 claimed ETH DOWN", at: minutesAgo(44) },
];

export const delay = <T,>(value: T, ms = 420): Promise<T> =>
  new Promise((resolve) => setTimeout(() => resolve(value), ms));
