/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MyDropsRouteImport } from './routes/my-drops'
import { Route as ClaimCodeRouteImport } from './routes/claim.$code'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PositionPositionIdRouteImport } from './routes/position.$positionId'
import { Route as DashboardCampaignCampaignIdRouteImport } from './routes/dashboard/campaign.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDropsRoute = MyDropsRouteImport.update({
  id: '/my-drops',
  path: '/my-drops',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimCodeRoute = ClaimCodeRouteImport.update({
  id: '/claim/$code',
  path: '/claim/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PositionPositionIdRoute = PositionPositionIdRouteImport.update({
  id: '/position/$positionId',
  path: '/position/$positionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCampaignCampaignIdRoute =
  DashboardCampaignCampaignIdRouteImport.update({
    id: '/campaign/$campaignId',
    path: '/campaign/$campaignId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/my-drops': typeof MyDropsRoute
  '/claim/$code': typeof ClaimCodeRoute
  '/position/$positionId': typeof PositionPositionIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaign/$campaignId': typeof DashboardCampaignCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/my-drops': typeof MyDropsRoute
  '/claim/$code': typeof ClaimCodeRoute
  '/position/$positionId': typeof PositionPositionIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/campaign/$campaignId': typeof DashboardCampaignCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/my-drops': typeof MyDropsRoute
  '/claim/$code': typeof ClaimCodeRoute
  '/position/$positionId': typeof PositionPositionIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaign/$campaignId': typeof DashboardCampaignCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/dashboard'
    | '/explore'
    | '/my-drops'
    | '/claim/$code'
    | '/position/$positionId'
    | '/dashboard/'
    | '/dashboard/campaign/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/explore'
    | '/my-drops'
    | '/claim/$code'
    | '/position/$positionId'
    | '/dashboard'
    | '/dashboard/campaign/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/dashboard'
    | '/explore'
    | '/my-drops'
    | '/claim/$code'
    | '/position/$positionId'
    | '/dashboard/'
    | '/dashboard/campaign/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  MyDropsRoute: typeof MyDropsRoute
  ClaimCodeRoute: typeof ClaimCodeRoute
  PositionPositionIdRoute: typeof PositionPositionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-drops': {
      id: '/my-drops'
      path: '/my-drops'
      fullPath: '/my-drops'
      preLoaderRoute: typeof MyDropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$code': {
      id: '/claim/$code'
      path: '/claim/$code'
      fullPath: '/claim/$code'
      preLoaderRoute: typeof ClaimCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/position/$positionId': {
      id: '/position/$positionId'
      path: '/position/$positionId'
      fullPath: '/position/$positionId'
      preLoaderRoute: typeof PositionPositionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/campaign/$campaignId': {
      id: '/dashboard/campaign/$campaignId'
      path: '/campaign/$campaignId'
      fullPath: '/dashboard/campaign/$campaignId'
      preLoaderRoute: typeof DashboardCampaignCampaignIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCampaignCampaignIdRoute: typeof DashboardCampaignCampaignIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCampaignCampaignIdRoute: DashboardCampaignCampaignIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExploreRoute: ExploreRoute,
  MyDropsRoute: MyDropsRoute,
  ClaimCodeRoute: ClaimCodeRoute,
  PositionPositionIdRoute: PositionPositionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
